require_relative '../setup'
require_relative './exercise_1'
require_relative './exercise_2'
require_relative './exercise_3'
require_relative './exercise_4'

puts "Exercise 5"
puts "----------"

# Your code goes here ...
@total_revenue=Store.sum(:annual_revenue)
@total_stores=Store.count
@rich_stores=Store.where("annual_revenue > 1000000").count

p "Total revenue generated by total of #{@total_stores} stores in DB is: #{@total_revenue}."
p "Average revenue generated by total of #{@total_stores} stores in DB is: #{(@total_revenue/@total_stores)}."
p "Number of stores generating more than $1M #{@rich_stores >1? 'are:' : 'is:'} #{@rich_stores}"